import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.52.1'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface EmailGenerationRequest {
  prompt: string;
  subject: string;
  styleGuide?: {
    brandName: string;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    fontFamily: string;
    tone: string;
    brandVoice: string;
    emailSignature: string;
  };
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Initialize Supabase client
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Skip authentication for demo purposes
    const demoUserId = '550e8400-e29b-41d4-a716-446655440000';

    const { prompt, subject, styleGuide }: EmailGenerationRequest = await req.json();

    if (!prompt || !subject) {
      throw new Error('Missing required fields: prompt and subject');
    }

    // Get Claude API key from secrets
    const claudeApiKey = Deno.env.get('CLAUDE_API_KEY');
    if (!claudeApiKey) {
      throw new Error('Claude API key not configured');
    }

    // Prepare the prompt for Claude
    const systemPrompt = `CRITICAL RULES:
1. DO NOT write "We hope this message finds you well"
2. DO NOT write "Your request:" followed by what they asked for
3. DO NOT write meta-commentary about the email template being "beautifully crafted" or "designed to be engaging"
4. DO NOT write generic corporate phrases
5. Just write the actual email content they requested

Style with HTML/CSS:
- Background: gradient from ${styleGuide?.primaryColor || '#684cff'} to ${styleGuide?.secondaryColor || '#22d3ee'}
- Content: white container, simple clean layout
- Font: ${styleGuide?.fontFamily || 'Arial, sans-serif'}

Include {{name}} and {{unsubscribe_url}} placeholders
Sign off with: ${styleGuide?.emailSignature || 'Best regards,\\nThe Team'}`;

    const userPrompt = `Write an email about: "${prompt}"
Subject should be: "${subject}"

Write it like a normal person would write an email. No corporate speak. Just natural, direct communication.`;

    // Call Claude API
    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': claudeApiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        messages: [
          {
            role: 'user',
            content: `${systemPrompt}\n\n${userPrompt}`
          }
        ],
      }),
    });

    if (!claudeResponse.ok) {
      const errorText = await claudeResponse.text();
      console.error('Claude API error:', errorText);
      throw new Error(`Claude API error: ${claudeResponse.status}`);
    }

    const claudeData = await claudeResponse.json();
    const generatedHtml = claudeData.content[0]?.text || '';

    if (!generatedHtml) {
      throw new Error('No content generated by Claude');
    }

    // Log the successful generation
    console.log('Email template generated successfully');

    return new Response(
      JSON.stringify({
        success: true,
        htmlContent: generatedHtml,
        metadata: {
          subject,
          userId: demoUserId,
          generatedAt: new Date().toISOString(),
        }
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error) {
    console.error('Error in generate-email function:', error);
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message || 'Internal server error',
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});