import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.52.1'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface EmailGenerationRequest {
  prompt: string;
  subject: string;
  styleGuide?: {
    brandName: string;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    fontFamily: string;
    tone: string;
    brandVoice: string;
    emailSignature: string;
  };
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Initialize Supabase client
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Skip authentication for demo purposes
    const demoUserId = '550e8400-e29b-41d4-a716-446655440000';

    const { prompt, subject, styleGuide }: EmailGenerationRequest = await req.json();

    if (!prompt || !subject) {
      throw new Error('Missing required fields: prompt and subject');
    }

    // Get Claude API key from secrets
    const claudeApiKey = Deno.env.get('CLAUDE_API_KEY');
    if (!claudeApiKey) {
      throw new Error('Claude API key not configured');
    }

    // Optimized prompt for faster, better generation
    const emailTemplate = `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${subject}</title>
</head>
<body style="margin: 0; padding: 0; font-family: ${styleGuide?.fontFamily || 'Arial, sans-serif'}; background-color: #f5f5f5;">
    <div style="max-width: 600px; margin: 0 auto; background-color: white;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, ${styleGuide?.primaryColor || '#758565'}, ${styleGuide?.secondaryColor || '#374151'}); color: white; text-align: center; padding: 40px 20px;">
            <h1 style="margin: 0; font-size: 32px; font-weight: bold;">${styleGuide?.brandName || 'Your Brand'}</h1>
            <h2 style="margin: 10px 0 0 0; font-size: 24px; font-weight: normal; opacity: 0.9;">${subject}</h2>
        </div>
        
        <!-- Content -->
        <div style="padding: 40px 30px;">
            <p style="margin: 0 0 20px 0; font-size: 16px; line-height: 1.6; color: #333;">Dear {{name}},</p>
            
            <div id="ai-content">
                <!-- AI will replace this with actual content -->
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
                <a href="#" style="display: inline-block; background-color: ${styleGuide?.primaryColor || '#758565'}; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold;">Take Action</a>
            </div>
        </div>
        
        <!-- Footer -->
        <div style="padding: 20px 30px; background-color: #f9f9f9; border-top: 1px solid #eee; text-align: center;">
            <p style="margin: 0 0 10px 0; font-size: 14px; color: #666; white-space: pre-line;">${styleGuide?.emailSignature || 'Best regards,\\nThe Team'}</p>
            <p style="margin: 10px 0 0 0; font-size: 12px; color: #999;">
                <a href="https://mixifcnokcmxarpzwfiy.supabase.co/functions/v1/unsubscribe?email={{email}}" style="color: #999;">Unsubscribe</a>
            </p>
        </div>
    </div>
</body>
</html>`;

    // Short, focused prompt for speed
    const contentPrompt = `Write email content for "${prompt}" in ${styleGuide?.tone || 'friendly'} tone for ${styleGuide?.brandName || 'Your Brand'}. 
    
Brand voice: ${styleGuide?.brandVoice || 'Professional yet approachable'}

Write 2-3 paragraphs of engaging content only. No subject, no greetings, no signature. Just the main content paragraphs.`;

    // Use faster model for speed optimization
    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': claudeApiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-3-5-haiku-20241022', // Faster model
        max_tokens: 800, // Reduced token limit for speed
        messages: [
          {
            role: 'user',
            content: contentPrompt
          }
        ],
      }),
    });

    if (!claudeResponse.ok) {
      const errorText = await claudeResponse.text();
      console.error('Claude API error:', errorText);
      throw new Error(`Claude API error: ${claudeResponse.status}`);
    }

    const claudeData = await claudeResponse.json();
    let aiContent = claudeData.content[0]?.text || '';

    if (!aiContent) {
      throw new Error('No content generated by Claude');
    }

    // Clean up AI content
    aiContent = aiContent
      .replace(/```html\n?/g, '')
      .replace(/```\n?/g, '')
      .trim();

    // Insert AI content into template
    let finalHtml = emailTemplate.replace(
      '<div id="ai-content">',
      `<div id="ai-content"><div style="font-size: 16px; line-height: 1.6; color: #333;">${aiContent.split('\n').map(p => p.trim() ? `<p style="margin: 0 0 20px 0;">${p}</p>` : '').join('')}</div>`
    );

    console.log('Optimized email template generated successfully');

    return new Response(
      JSON.stringify({
        success: true,
        htmlContent: finalHtml,
        metadata: {
          subject,
          userId: demoUserId,
          generatedAt: new Date().toISOString(),
        }
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error) {
    console.error('Error in generate-email function:', error);
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message || 'Internal server error',
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});