import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.52.1'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface EmailEditRequest {
  htmlContent: string;
  editInstruction: string;
  themeColors?: {
    primary: string;
    secondary: string;
    accent: string;
  };
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { htmlContent, editInstruction, themeColors }: EmailEditRequest = await req.json();

    if (!htmlContent || !editInstruction) {
      throw new Error('Missing required fields: htmlContent and editInstruction');
    }

    // Get Claude API key from secrets
    const claudeApiKey = Deno.env.get('CLAUDE_API_KEY');
    if (!claudeApiKey) {
      throw new Error('Claude API key not configured');
    }

    // Prepare the prompt for Claude
    const systemPrompt = `You are an expert email editor. You will be given:
1. An existing HTML email template
2. An instruction to modify it

Your task is to modify the HTML email according to the instruction. IMPORTANT RULES:
- Return ONLY the modified HTML, no explanations or comments
- Keep the overall structure intact unless specifically asked to change it
- Preserve any {{name}} and {{unsubscribe_url}} placeholders
- If the instruction mentions removing background, replace gradient backgrounds with clean white/light backgrounds
- If colors are mentioned, use the provided theme colors: primary=${themeColors?.primary || '#684cff'}, secondary=${themeColors?.secondary || '#22d3ee'}, accent=${themeColors?.accent || '#34d399'}
- Make sure the email remains responsive and email-client friendly`;

    const userPrompt = `EXISTING EMAIL HTML:
${htmlContent}

EDIT INSTRUCTION: ${editInstruction}

Return the modified HTML:`;

    // Call Claude API
    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': claudeApiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        messages: [
          {
            role: 'user',
            content: `${systemPrompt}\n\n${userPrompt}`
          }
        ],
      }),
    });

    if (!claudeResponse.ok) {
      const errorText = await claudeResponse.text();
      console.error('Claude API error:', errorText);
      throw new Error(`Claude API error: ${claudeResponse.status}`);
    }

    const claudeData = await claudeResponse.json();
    let editedHtml = claudeData.content[0]?.text || '';

    if (!editedHtml) {
      throw new Error('No content generated by Claude');
    }

    // Clean up any markdown formatting that might have been added
    editedHtml = editedHtml.replace(/^```html\n?/i, '').replace(/\n?```$/i, '').trim();

    // Log the successful edit
    console.log('Email template edited successfully');

    return new Response(
      JSON.stringify({
        success: true,
        htmlContent: editedHtml,
        metadata: {
          editedAt: new Date().toISOString(),
        }
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error) {
    console.error('Error in edit-email function:', error);
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message || 'Internal server error',
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});